Repository openshift/managed-scripts, pull requests merged in 2021-12, with the labels that each got.

#40 move get-kafka-instance-state script under CEE
  scripts/CEE/get-kafka-instance-state/get-kafka-instance-state.sh
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: lgtm

#41 Add RBAC for managedkafka and kafka resources
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: ok-to-test, lgtm, approved

#42 Add missing permissions to kafka-instances script
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: needs-ok-to-test, lgtm, approved

#43 Fixed malformed metadata for get-kakfa-instance-state
  hack/metadata.schema.json
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: lgtm, approved
