Repository openshift/managed-scripts, pull requests merged in 2021-11, with the labels that each got.

#28 Add tsdb status script
  .gitignore
  scripts/SREP/tsdb-status/metadata.yaml
  scripts/SREP/tsdb-status/script.sh
Labels: lgtm, approved

#29 Move etc health check script
  scripts/CEE/etcd-health-check/metadata.yaml
  scripts/CEE/etcd-health-check/script.sh
Labels: lgtm, approved

#30 OSD-8555 allow CEE to read node-logs
  scripts/SREP/node-logs/metadata.yaml
  scripts/SREP/node-logs/script.sh
Labels: lgtm, approved

#32 [OSD-8686] Convert v4-registry-s3-size script to managed-script
  Dockerfile
  scripts/CEE/registry-s3-bucket-size/metadata.yaml
  scripts/CEE/registry-s3-bucket-size/script.sh
Labels: lgtm, approved

#34 Add get-targets-down script
  Dockerfile
  scripts/SREP/get-targets-down/metadata.yaml
  scripts/SREP/get-targets-down/script.sh
Labels: lgtm, approved

#35 get-targets-down: Use internal prometheus domain name
  scripts/SREP/get-targets-down/metadata.yaml
  scripts/SREP/get-targets-down/script.sh
Labels: lgtm, approved

#38 Update OWNERS file
  OWNERS
Labels: approved

#36 Add get Kafka instance state script
  scripts/managed-services/get-kafka-instance-state/get-kafka-instance-state.sh
  scripts/managed-services/get-kafka-instance-state/metadata.yaml
Labels: ok-to-test, lgtm, approved
