Repository openshift/managed-scripts, pull requests merged in 2022-03, with the labels that each got.

#55 Adding get rhosak operator script
  scripts/CEE/get-rhosak-operators/get-rhosak-operators.sh
  scripts/CEE/get-rhosak-operators/metadata.yaml
Labels: lgtm, approved

#56 Fixing tar output
  scripts/CEE/get-rhosak-operators/get-rhosak-operators.sh
  scripts/CEE/get-rhosak-operators/metadata.yaml
Labels: lgtm, approved

#58 CSSRE-1943: add lib folder in CSSRE dir and package install in Dockerfile
  Dockerfile
  scripts/CSSRE/lib/__init__.py
  scripts/CSSRE/lib/py/__init__.py
  scripts/CSSRE/lib/py/command.py
  scripts/CSSRE/lib/py/exceptions.py
  scripts/CSSRE/lib/py/logger.py
  scripts/CSSRE/lib/py/script.py
Labels: ok-to-test, lgtm, approved

#59 Adding Supreeth and Mitali as reviewers
  OWNERS
Labels: lgtm, approved

#60 CSSRE-1853: add get-node-restart script
  .gitignore
  scripts/CSSRE/get-node-restarts/README.md
  scripts/CSSRE/get-node-restarts/metadata.yaml
  scripts/CSSRE/get-node-restarts/script.py
Labels: ok-to-test, lgtm, approved

#62 CSSRE-1942: add owners in CSSRE directory
  scripts/CSSRE/OWNERS
Labels: needs-ok-to-test, lgtm, approved

#63 Rename get-rhosak-operators to match directory
  scripts/CEE/get-rhosak-operators/metadata.yaml
Labels: lgtm, approved

#52 Add commands to list and get must-gathers from hive s3 buckets
  scripts/SREP/mg-log-extractor/metadata.yaml
  scripts/SREP/mg-log-extractor/script.sh
  scripts/SREP/mg-log-ls/metadata.yaml
  scripts/SREP/mg-log-ls/script.sh
Labels: lgtm, approved
