Repository openshift/managed-scripts, pull requests merged in 2022-01, with the labels that each got.

#44 Add endpointslice list permission
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: lgtm, approved

#46 Add optional since/since-time flags as environment variables
  scripts/CEE/get-kafka-instance-state/get-kafka-instance-state.sh
  scripts/CEE/get-kafka-instance-state/metadata.yaml
Labels: ok-to-test, lgtm, approved

#48 OSD-9511: Enable CEE to identify if customer is running any tech preview feature
  scripts/CEE/check-tech-preview-features/README.md
  scripts/CEE/check-tech-preview-features/metadata.yml
  scripts/CEE/check-tech-preview-features/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#49 renamed matadata.yml to metadata.yaml
  scripts/CEE/check-tech-preview-features/metadata.yaml
Labels: lgtm, approved

#47 OSD-8682 Converting elastic search status script to managed-scripts
  scripts/SREP/elasticsearch-status/metadata.yaml
  scripts/SREP/elasticsearch-status/script.sh
Labels: lgtm, approved

#50 OSD-8688 Add cluster-operator-status script
  scripts/SREP/cluster-operator-status/README.md
  scripts/SREP/cluster-operator-status/metadata.yaml
  scripts/SREP/cluster-operator-status/script.sh
Labels: lgtm, approved

#51 Update OWNERS
  OWNERS
Labels: lgtm, approved
