Repository openshift/managed-scripts, pull requests merged in 2023-08, with the labels that each got.

#120 [OSD-17593] add hypershift binary to base image
  Dockerfile
Labels: lgtm, approved

#119 OSD-17592: Added script for etcd complete health check
  scripts/SREP/etcd-complete-health-check/README.md
  scripts/SREP/etcd-complete-health-check/metadata.yaml
  scripts/SREP/etcd-complete-health-check/script.sh
Labels: lgtm, approved, jira/valid-reference

#122 OSD-17959: Add yq binary into managed-scripts container image
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#126 Remove all references of CS/MT SRE
  scripts/CEE/check-tech-preview-features/metadata.yaml
  scripts/CEE/cluster-health-check/metadata.yaml
  scripts/CEE/describe-kafka-transaction/metadata.yaml
  scripts/CEE/etcd-health-check/metadata.yaml
  scripts/CEE/get-kafka-instance-state/metadata.yaml
  scripts/CEE/get-rhoc-connector-info/metadata.yaml
  scripts/CEE/get-rhosak-operators/metadata.yaml
  scripts/CEE/hs-must-gather/metadata.yaml
  scripts/CEE/list-alerts/metadata.yaml
  scripts/LPSRE/OWNERS
  scripts/LPSRE/get-kafka-topics/README.md
  scripts/LPSRE/get-kafka-topics/get-kafka-topics.py
  scripts/LPSRE/get-kafka-topics/metadata.yaml
  scripts/LPSRE/get-node-restarts/README.md
  scripts/LPSRE/get-node-restarts/metadata.yaml
  scripts/LPSRE/get-node-restarts/script.py
  scripts/LPSRE/lib/__init__.py
  scripts/LPSRE/lib/py/__init__.py
  scripts/LPSRE/lib/py/command.py
  scripts/LPSRE/lib/py/exceptions.py
  scripts/LPSRE/lib/py/kafka.py
  scripts/LPSRE/lib/py/logger.py
  scripts/LPSRE/lib/py/script.py
  scripts/LPSRE/lib/py/settings.py
  scripts/LPSRE/rolling-restart-brokers/README.md
  scripts/LPSRE/rolling-restart-brokers/metadata.yaml
  scripts/LPSRE/rolling-restart-brokers/rolling-restart-brokers.sh
  scripts/LPSRE/under-min-isr-partitions/README.md
  scripts/LPSRE/under-min-isr-partitions/metadata.yaml
  scripts/LPSRE/under-min-isr-partitions/under-min-isr-partitions.py
  scripts/LPSRE/under-replicated-partitions/README.md
  scripts/LPSRE/under-replicated-partitions/metadata.yaml
  scripts/LPSRE/under-replicated-partitions/under-replicated-partitions.py
  scripts/SREP/cluster-operator-status/metadata.yaml
  scripts/SREP/delete-olm-operator/metadata.yaml
  scripts/SREP/describe-nodes/metadata.yaml
  scripts/SREP/elasticsearch-status/metadata.yaml
  scripts/SREP/etcd-complete-health-check/metadata.yaml
  scripts/SREP/example/metadata.yaml
  scripts/SREP/get-targets-down/metadata.yaml
  scripts/SREP/node-logs/metadata.yaml
  scripts/SREP/tsdb-status/metadata.yaml
Labels: lgtm, tide/merge-method-squash, approved

#127 Add supreeth7 as an approver
  OWNERS
Labels: lgtm, approved

#124 OSD-17611 : Adding information on Managed Scripts release cycles
  README.md
Labels: lgtm, tide/merge-method-squash, approved
