Repository openshift/managed-scripts, pull requests merged in 2023-12, with the labels that each got.

#157 OSD-19605 a script to extract email from pull secret
  scripts/SREP/get-pull-secret-email/README.md
  scripts/SREP/get-pull-secret-email/metadata.yaml
  scripts/SREP/get-pull-secret-email/script.sh
Labels: lgtm, approved

#160 OSD-19453: Drain reboot worker nodes
  scripts/CEE/drain-reboot-nodes/README.md
  scripts/CEE/drain-reboot-nodes/metadata.yaml
  scripts/CEE/drain-reboot-nodes/script.sh
Labels: lgtm, tide/merge-method-squash, approved, jira/valid-reference

#162 OSD-19453: drain-reboot-worker-node script
  scripts/CEE/drain-reboot-worker-node/README.md
  scripts/CEE/drain-reboot-worker-node/metadata.yaml
  scripts/CEE/drain-reboot-worker-node/script.sh
Labels: lgtm, approved, jira/valid-reference

#136 Add a script to delete a machine
  scripts/CEE/delete-worker-node/README.md
  scripts/CEE/delete-worker-node/metadata.yaml
  scripts/CEE/delete-worker-node/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#163 Managed Scripts: Fixing path issues
  scripts/CEE/cordon-uncordon-worker-node/README.md
  scripts/CEE/cordon-uncordon-worker-node/metadata.yaml
  scripts/CEE/cordon-uncordon-worker-node/script.sh
  scripts/CEE/drain-reboot-worker-node/README.md
Labels: lgtm, approved

#164 Remove return 1 when no failed jobs are found..
  scripts/SREP/retry-failed-pruning-cronjob/script.sh
Labels: lgtm, approved
