Repository openshift/managed-scripts, pull requests merged in 2023-09, with the labels that each got.

#123 OSD-17842: Create a managed-script for SREP team to update the upgrade policy state
  Dockerfile
  scripts/SREP/update-upgrade-policy-state/README.md
  scripts/SREP/update-upgrade-policy-state/metadata.yaml
  scripts/SREP/update-upgrade-policy-state/script.sh
Labels: lgtm, approved, jira/valid-reference

#121 OSD-17639 - Add full hypershift dump
  scripts/CEE/hs-must-gather/README.md
  scripts/CEE/hs-must-gather/metadata.yaml
  scripts/CEE/hs-must-gather/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#125 cordon-uncordon-nodes script
  scripts/CEE/cordon-uncordon-nodes/README.md
  scripts/CEE/cordon-uncordon-nodes/metadata.yaml
  scripts/CEE/cordon-uncordon-nodes/script.sh
Labels: lgtm, approved

#129 Adds a managed script for pruning orphaned blobs from the image registry
  scripts/SREP/hard-prune-image-registry/metadata.yaml
  scripts/SREP/hard-prune-image-registry/script.sh
Labels: lgtm, approved

#130 osd-17784: addind check-jsonschema to Dockerfile
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#131 osd-17784: changing schema validation script
  hack/schema_validation.sh
Labels: lgtm, approved, jira/valid-reference

#132 osd-17784: fixing json schema and a metadata.yaml
  hack/metadata.schema.json
  scripts/LPSRE/rolling-restart-brokers/metadata.yaml
Labels: lgtm, approved, jira/valid-reference

#128 Removing the sensitive files from the hypershift dump
  scripts/CEE/hs-must-gather/README.md
  scripts/CEE/hs-must-gather/script.sh
Labels: lgtm, approved

#137 Add SFTP upload function
  Dockerfile
  scripts/lib/sftp_upload/lib.sh
Labels: lgtm, approved

#138 OSD-17674 Upload the must gather tarball to SFTP
  scripts/CEE/hs-must-gather/README.md
  scripts/CEE/hs-must-gather/script.sh
Labels: lgtm, approved

#135 osd-18431: schema_validation.sh improvements
  Makefile
  README.md
  hack/schema_validation.sh
  hack/yamltojson.py
Labels: lgtm, tide/merge-method-squash, approved, jira/valid-reference

#139 Minor improvements over hyperhift must gather script
  scripts/CEE/hs-must-gather/metadata.yaml
  scripts/CEE/hs-must-gather/script.sh
  scripts/lib/sftp_upload/lib.sh
Labels: lgtm, approved

#140 osd-18602-updated-files
  scripts/LPSRE/get-kafka-topics/README.md
  scripts/LPSRE/get-kafka-topics/get-kafka-topics.py
  scripts/LPSRE/get-node-restarts/README.md
  scripts/LPSRE/get-node-restarts/script.py
  scripts/LPSRE/rolling-restart-brokers/README.md
  scripts/LPSRE/under-min-isr-partitions/README.md
  scripts/LPSRE/under-min-isr-partitions/under-min-isr-partitions.py
  scripts/LPSRE/under-replicated-partitions/README.md
  scripts/LPSRE/under-replicated-partitions/under-replicated-partitions.py
Labels: lgtm, approved

#141 OSD-18647 - Only deletes Secrets, SecretList and Certificates
  scripts/CEE/hs-must-gather/script.sh
Labels: lgtm, approved

#142 osd-18432: updating python release
  Dockerfile
Labels: lgtm, approved, jira/valid-reference
