Repository openshift/managed-scripts, pull requests merged in 2024-06, with the labels that each got.

#190 [OSD-19695] make sure the binaries are up to date
  Dockerfile
Labels: lgtm, approved

#191 Revert "Add script for OCPBUGS-33377 workaround"
  .gitignore
  scripts/SREP/ocpbugs-33377-workaround/README.md
  scripts/SREP/ocpbugs-33377-workaround/metadata.yaml
  scripts/SREP/ocpbugs-33377-workaround/script.sh
Labels: lgtm, approved

#189 osd23682: consolidating cordon/drain/reboot worker nodes
  scripts/CEE/worker-node-operations/README.md
  scripts/CEE/worker-node-operations/metadata.yaml
  scripts/CEE/worker-node-operations/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#192 OSD-23925: flag customer data facing scripts
  hack/metadata.schema.json
  scripts/CEE/check-tech-preview-features/metadata.yaml
  scripts/CEE/cluster-health-check/metadata.yaml
  scripts/CEE/cordon-uncordon-worker-node/metadata.yaml
  scripts/CEE/delete-worker-node/metadata.yaml
  scripts/CEE/describe-kafka-transaction/metadata.yaml
  scripts/CEE/etcd-health-check/metadata.yaml
  scripts/CEE/get-events/metadata.yaml
  scripts/CEE/get-kafka-instance-state/metadata.yaml
  scripts/CEE/get-rhoc-connector-info/metadata.yaml
  scripts/CEE/get-rhosak-operators/metadata.yaml
  scripts/CEE/hs-must-gather/metadata.yaml
  scripts/CEE/kubelet-restart/metadata.yaml
  scripts/CEE/list-alerts/metadata.yaml
  scripts/CEE/pcap-collector/metadata.yaml
  scripts/CEE/registry-s3-bucket-size/metadata.yaml
  scripts/CEE/restart-dns-default/metadata.yaml
  scripts/CEE/worker-node-operations/metadata.yaml
  scripts/LPSRE/increasing-observability-operator-pvc-size/metadata.yaml
  scripts/SREP/cluster-operator-status/metadata.yaml
  scripts/SREP/delete-olm-operator/metadata.yaml
  scripts/SREP/describe-nodes/metadata.yaml
  scripts/SREP/elasticsearch-status/metadata.yaml
  scripts/SREP/etcd-complete-health-check/metadata.yaml
  scripts/SREP/example/metadata.yaml
  scripts/SREP/get-pull-secret-email/metadata.yaml
  scripts/SREP/get-targets-down/metadata.yaml
  scripts/SREP/hard-prune-image-registry/metadata.yaml
  scripts/SREP/infra-node-resize/metadata.yaml
  scripts/SREP/manage-silence/metadata.yaml
  scripts/SREP/mg-log-extractor/metadata.yaml
  scripts/SREP/mg-log-ls/metadata.yaml
  scripts/SREP/node-drain-reboot/metadata.yaml
  scripts/SREP/node-logs/metadata.yaml
  scripts/SREP/replace-master/metadata.yaml
  scripts/SREP/retry-failed-pruning-cronjob/metadata.yaml
  scripts/SREP/tsdb-status/metadata.yaml
  scripts/SREP/update-upgrade-policy-state/metadata.yaml
  scripts/examples/lib-sourcer/metadata.yaml
  template/metadata.yaml
Labels: lgtm, approved, jira/valid-reference

#188 Feature cluster autoscaler logs
  scripts/CEE/collect-verbose-ca-logs/README.md
  scripts/CEE/collect-verbose-ca-logs/metadata.yaml
  scripts/CEE/collect-verbose-ca-logs/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#194 Osd23682: Fixing README file
  scripts/CEE/worker-node-operations/README.md
Labels: lgtm, approved
