Repository openshift/managed-scripts, pull requests merged in 2025-03, with the labels that each got.

#211 Fix update-upgrade-policy-state script
  scripts/SREP/update-upgrade-policy-state/README.md
  scripts/SREP/update-upgrade-policy-state/metadata.yaml
  scripts/SREP/update-upgrade-policy-state/script.sh
Labels: lgtm, tide/merge-method-squash, approved

#214 OSD-19235:Adding Contributing.md
  CONTRIBUTING.md
Labels: lgtm, approved, jira/valid-reference

#213 Update README.md
  scripts/CEE/delete-worker-node/README.md
Labels: lgtm, approved
